# Generated by Django 5.2.14 on 2026-06-15 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_bill_markup_percent_tenant_referral_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('last_input', models.CharField(blank=True, max_length=255)),
                ('last_response', models.TextField(blank=True)),
                ('ended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'ussd_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='ussd_sessio_session_0554d9_idx')],
            },
        ),
    ]
