# Generated by Django 6.0.5 on 2026-05-27 21:16

import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in X-Tenant-Slug header and subdomain routing', unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#6C63FF', help_text='Hex color', max_length=7)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('airtime_markup_percent', models.DecimalField(decimal_places=2, default=0, help_text='Extra % charged on airtime purchases', max_digits=5)),
                ('data_markup_percent', models.DecimalField(decimal_places=2, default=0, help_text='Extra % charged on data purchases', max_digits=5)),
                ('min_wallet_fund', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('max_daily_transaction', models.DecimalField(decimal_places=2, default=500000, help_text='Max total daily spend per user (NGN)', max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
