# Generated by Django 5.2.14 on 2026-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bill_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra % charged on electricity/TV bill payments', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wallet bonus credited to referrer on referee first successful purchase', max_digits=10),
        ),
    ]
