# Generated by Django 5.2.14 on 2026-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_bill_markup_percent_tenant_referral_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='min_withdrawal',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Minimum withdrawal amount (NGN)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat fee charged per withdrawal (NGN)', max_digits=10),
        ),
    ]
