# Generated by Django 5.2.14 on 2026-06-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '__first__'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Meter or smartcard number', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, help_text='Disco / cable provider code', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, help_text='Electricity token returned by provider', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='variation_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'Cable TV'), ('wallet_fund', 'Wallet Fund'), ('refund', 'Refund'), ('commission', 'Agent Commission')], max_length=20),
        ),
    ]
