# Generated by Django 5.2.14 on 2026-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_agent_transaction_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'Cable TV'), ('wallet_fund', 'Wallet Fund'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('commission', 'Agent Commission')], max_length=20),
        ),
    ]
