from decimal import Decimal
from unittest.mock import patch
from django.test import TestCase
from apps.tenants.models import Tenant
from apps.authentication.models import User
from apps.wallet.models import Wallet
from apps.transactions.models import Transaction
from apps.transactions.fulfillment import fulfill
from .models import ReferralReward


class ReferralRewardTests(TestCase):
    def setUp(self):
        self.tenant = Tenant.objects.create(
            name='Test', slug='test-tenant', owner_email='t@t.com',
            owner_phone='+2348000000000', referral_bonus=Decimal('100'),
        )
        self.referrer = User.objects.create_user(phone_number='+2348000000001', tenant=self.tenant, password='p')
        self.referrer_wallet = Wallet.objects.create(tenant=self.tenant, user=self.referrer, balance=Decimal('0'))
        self.referee = User.objects.create_user(
            phone_number='+2348000000002', tenant=self.tenant, password='p', referred_by=self.referrer,
        )
        self.referee_wallet = Wallet.objects.create(tenant=self.tenant, user=self.referee, balance=Decimal('1000'))

    def _airtime(self):
        return Transaction.objects.create(
            tenant=self.tenant, user=self.referee, type='airtime',
            amount=Decimal('200'), face_value=Decimal('200'), status='pending',
            reference=Transaction.generate_reference(), network='mtn', phone_number='+2348011111111',
        )

    @patch('apps.airtime.services.purchase_airtime')
    def test_first_success_rewards_referrer_once(self, mock_purchase):
        mock_purchase.return_value = {'success': True, 'reference': 'GL-1', 'message': 'ok'}

        fulfill(self._airtime())
        self.referrer_wallet.refresh_from_db()
        self.assertEqual(self.referrer_wallet.balance, Decimal('100'))
        self.assertEqual(ReferralReward.all_objects.filter(referrer=self.referrer).count(), 1)

        # Second purchase must NOT pay again.
        fulfill(self._airtime())
        self.referrer_wallet.refresh_from_db()
        self.assertEqual(self.referrer_wallet.balance, Decimal('100'))
        self.assertEqual(ReferralReward.all_objects.filter(referrer=self.referrer).count(), 1)

    def test_referral_code_autogenerated(self):
        self.assertTrue(self.referrer.referral_code)
        self.assertEqual(len(self.referrer.referral_code), 8)
