# Generated by Django 5.2.14 on 2026-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_mode', models.BooleanField(default=True, help_text='ON: mock providers + test OTP (development). OFF: live providers + real OTP (production).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Runtime configuration',
                'verbose_name_plural': 'Runtime configuration',
            },
        ),
    ]
